[package]
name = "web"
version = "0.1.0"
edition = "2021"

[dependencies]
shared = { path = "../shared" }
axum = "0.7.2"
tokio = { version = "1", features = ["full"] }
uuid = { workspace = true, version = "1.11.0" }
